### ISSUE TITLE
UTF-8 Fonts

### ISSUE THREAD

**Issue by markeganfuller** [markeganfuller/pytextgraph#2]
A number of fonts show the whole block character differently from the other block characters, need to find a way around this.

**Comment by g1l3sp** [comment]
It would be nice to be able to customize the block character used for e.g. horizontal graphs.  In some terminals (depending on the chosen font, etc), there is no space between the full block characters on adjacent lines, which makes differentiating them visually tricky.  In our local version of graphs.py, I hacked the horizontal graph to use the "LOWER SEVEN EIGHTHS BLOCK (U+2587)" UTF-8 character: ▇

That solved this visual issue for me.  I imagine there may be cases where that continuous area graph style that I'm getting by default would be preferred, so adding a function to set the character to use would be a nice and flexible way to go.
